//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace MassRecord.PractitionerRegister {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServicesSoap", Namespace="http://tempuri.org")]
    public partial class WebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EditPractitionerRegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDictionaryItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PractitionerRegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePractitionerInformationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServices() {
            this.Url = global::MassRecord.Properties.Settings.Default.MassRecord_PractitionerRegister_WebServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EditPractitionerRegisterCompletedEventHandler EditPractitionerRegisterCompleted;
        
        /// <remarks/>
        public event GetDictionaryItemsCompletedEventHandler GetDictionaryItemsCompleted;
        
        /// <remarks/>
        public event PractitionerRegisterCompletedEventHandler PractitionerRegisterCompleted;
        
        /// <remarks/>
        public event UpdatePractitionerInformationCompletedEventHandler UpdatePractitionerInformationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.PractitionerRegister.EditPractitionerRegister", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse EditPractitionerRegister(string SystemCode, string UserName, string Password, PractitionerRegistrationObject PractitionerRegistration, long PractitionerID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool PractitionerIDSpecified) {
            object[] results = this.Invoke("EditPractitionerRegister", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        PractitionerRegistration,
                        PractitionerID,
                        PractitionerIDSpecified});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void EditPractitionerRegisterAsync(string SystemCode, string UserName, string Password, PractitionerRegistrationObject PractitionerRegistration, long PractitionerID, bool PractitionerIDSpecified) {
            this.EditPractitionerRegisterAsync(SystemCode, UserName, Password, PractitionerRegistration, PractitionerID, PractitionerIDSpecified, null);
        }
        
        /// <remarks/>
        public void EditPractitionerRegisterAsync(string SystemCode, string UserName, string Password, PractitionerRegistrationObject PractitionerRegistration, long PractitionerID, bool PractitionerIDSpecified, object userState) {
            if ((this.EditPractitionerRegisterOperationCompleted == null)) {
                this.EditPractitionerRegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditPractitionerRegisterOperationCompleted);
            }
            this.InvokeAsync("EditPractitionerRegister", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        PractitionerRegistration,
                        PractitionerID,
                        PractitionerIDSpecified}, this.EditPractitionerRegisterOperationCompleted, userState);
        }
        
        private void OnEditPractitionerRegisterOperationCompleted(object arg) {
            if ((this.EditPractitionerRegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditPractitionerRegisterCompleted(this, new EditPractitionerRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.PractitionerRegister.GetDictionaryItems", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DictionaryItemObject[] GetDictionaryItems(string SystemCode, string UserName, string Password) {
            object[] results = this.Invoke("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password});
            return ((DictionaryItemObject[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password) {
            this.GetDictionaryItemsAsync(SystemCode, UserName, Password, null);
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password, object userState) {
            if ((this.GetDictionaryItemsOperationCompleted == null)) {
                this.GetDictionaryItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDictionaryItemsOperationCompleted);
            }
            this.InvokeAsync("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password}, this.GetDictionaryItemsOperationCompleted, userState);
        }
        
        private void OnGetDictionaryItemsOperationCompleted(object arg) {
            if ((this.GetDictionaryItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDictionaryItemsCompleted(this, new GetDictionaryItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.PractitionerRegister.PractitionerRegister", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse PractitionerRegister(string SystemCode, string UserName, string Password, PractitionerRegistrationObject PractitionerRegistration, long PractitionerID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool PractitionerIDSpecified) {
            object[] results = this.Invoke("PractitionerRegister", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        PractitionerRegistration,
                        PractitionerID,
                        PractitionerIDSpecified});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PractitionerRegisterAsync(string SystemCode, string UserName, string Password, PractitionerRegistrationObject PractitionerRegistration, long PractitionerID, bool PractitionerIDSpecified) {
            this.PractitionerRegisterAsync(SystemCode, UserName, Password, PractitionerRegistration, PractitionerID, PractitionerIDSpecified, null);
        }
        
        /// <remarks/>
        public void PractitionerRegisterAsync(string SystemCode, string UserName, string Password, PractitionerRegistrationObject PractitionerRegistration, long PractitionerID, bool PractitionerIDSpecified, object userState) {
            if ((this.PractitionerRegisterOperationCompleted == null)) {
                this.PractitionerRegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPractitionerRegisterOperationCompleted);
            }
            this.InvokeAsync("PractitionerRegister", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        PractitionerRegistration,
                        PractitionerID,
                        PractitionerIDSpecified}, this.PractitionerRegisterOperationCompleted, userState);
        }
        
        private void OnPractitionerRegisterOperationCompleted(object arg) {
            if ((this.PractitionerRegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PractitionerRegisterCompleted(this, new PractitionerRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.PractitionerRegister.UpdatePractitionerInformation", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse UpdatePractitionerInformation(string SystemCode, string UserName, string Password, PractitionerInformationObject PractitionerInformation, long PractitionerID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool PractitionerIDSpecified) {
            object[] results = this.Invoke("UpdatePractitionerInformation", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        PractitionerInformation,
                        PractitionerID,
                        PractitionerIDSpecified});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePractitionerInformationAsync(string SystemCode, string UserName, string Password, PractitionerInformationObject PractitionerInformation, long PractitionerID, bool PractitionerIDSpecified) {
            this.UpdatePractitionerInformationAsync(SystemCode, UserName, Password, PractitionerInformation, PractitionerID, PractitionerIDSpecified, null);
        }
        
        /// <remarks/>
        public void UpdatePractitionerInformationAsync(string SystemCode, string UserName, string Password, PractitionerInformationObject PractitionerInformation, long PractitionerID, bool PractitionerIDSpecified, object userState) {
            if ((this.UpdatePractitionerInformationOperationCompleted == null)) {
                this.UpdatePractitionerInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePractitionerInformationOperationCompleted);
            }
            this.InvokeAsync("UpdatePractitionerInformation", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        PractitionerInformation,
                        PractitionerID,
                        PractitionerIDSpecified}, this.UpdatePractitionerInformationOperationCompleted, userState);
        }
        
        private void OnUpdatePractitionerInformationOperationCompleted(object arg) {
            if ((this.UpdatePractitionerInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePractitionerInformationCompleted(this, new UpdatePractitionerInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class PractitionerRegistrationObject {
        
        private string beeperNumberField;
        
        private string categoriesForCoverageField;
        
        private string cellPhoneField;
        
        private System.DateTime dateOfBirthField;
        
        private bool dateOfBirthFieldSpecified;
        
        private string disciplineField;
        
        private string educationLevelField;
        
        private string ethnicOriginField;
        
        private string homeCityField;
        
        private string homePhoneField;
        
        private string homeStateField;
        
        private string homeStreetField;
        
        private string homeZipCodeField;
        
        private string locatedInMedOfficeBuildingField;
        
        private string nameField;
        
        private string officeAddressCityField;
        
        private string officeAddressStateField;
        
        private string officeAddressStreetField;
        
        private string officeAddressZipCodeField;
        
        private string officeTelephone1Field;
        
        private string officeTelephone2Field;
        
        private string practitionerCategoryField;
        
        private string practitionerCredentialsField;
        
        private string practitionerSubTypeField;
        
        private string practitionerTypeField;
        
        private System.DateTime registrationDateField;
        
        private bool registrationDateFieldSpecified;
        
        private string sexField;
        
        private string aRRAReportableMeasuresField;
        
        private string aRRAPractitionerTypeField;
        
        private string nPINumberField;
        
        private string taxonomyCodeField;
        
        private string practitionerLanguageField;
        
        private string excludeFromCalendarField;
        
        /// <remarks/>
        public string BeeperNumber {
            get {
                return this.beeperNumberField;
            }
            set {
                this.beeperNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CategoriesForCoverage {
            get {
                return this.categoriesForCoverageField;
            }
            set {
                this.categoriesForCoverageField = value;
            }
        }
        
        /// <remarks/>
        public string CellPhone {
            get {
                return this.cellPhoneField;
            }
            set {
                this.cellPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfBirthSpecified {
            get {
                return this.dateOfBirthFieldSpecified;
            }
            set {
                this.dateOfBirthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Discipline {
            get {
                return this.disciplineField;
            }
            set {
                this.disciplineField = value;
            }
        }
        
        /// <remarks/>
        public string EducationLevel {
            get {
                return this.educationLevelField;
            }
            set {
                this.educationLevelField = value;
            }
        }
        
        /// <remarks/>
        public string EthnicOrigin {
            get {
                return this.ethnicOriginField;
            }
            set {
                this.ethnicOriginField = value;
            }
        }
        
        /// <remarks/>
        public string HomeCity {
            get {
                return this.homeCityField;
            }
            set {
                this.homeCityField = value;
            }
        }
        
        /// <remarks/>
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string HomeState {
            get {
                return this.homeStateField;
            }
            set {
                this.homeStateField = value;
            }
        }
        
        /// <remarks/>
        public string HomeStreet {
            get {
                return this.homeStreetField;
            }
            set {
                this.homeStreetField = value;
            }
        }
        
        /// <remarks/>
        public string HomeZipCode {
            get {
                return this.homeZipCodeField;
            }
            set {
                this.homeZipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LocatedInMedOfficeBuilding {
            get {
                return this.locatedInMedOfficeBuildingField;
            }
            set {
                this.locatedInMedOfficeBuildingField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string OfficeAddressCity {
            get {
                return this.officeAddressCityField;
            }
            set {
                this.officeAddressCityField = value;
            }
        }
        
        /// <remarks/>
        public string OfficeAddressState {
            get {
                return this.officeAddressStateField;
            }
            set {
                this.officeAddressStateField = value;
            }
        }
        
        /// <remarks/>
        public string OfficeAddressStreet {
            get {
                return this.officeAddressStreetField;
            }
            set {
                this.officeAddressStreetField = value;
            }
        }
        
        /// <remarks/>
        public string OfficeAddressZipCode {
            get {
                return this.officeAddressZipCodeField;
            }
            set {
                this.officeAddressZipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OfficeTelephone1 {
            get {
                return this.officeTelephone1Field;
            }
            set {
                this.officeTelephone1Field = value;
            }
        }
        
        /// <remarks/>
        public string OfficeTelephone2 {
            get {
                return this.officeTelephone2Field;
            }
            set {
                this.officeTelephone2Field = value;
            }
        }
        
        /// <remarks/>
        public string PractitionerCategory {
            get {
                return this.practitionerCategoryField;
            }
            set {
                this.practitionerCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string PractitionerCredentials {
            get {
                return this.practitionerCredentialsField;
            }
            set {
                this.practitionerCredentialsField = value;
            }
        }
        
        /// <remarks/>
        public string PractitionerSubType {
            get {
                return this.practitionerSubTypeField;
            }
            set {
                this.practitionerSubTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PractitionerType {
            get {
                return this.practitionerTypeField;
            }
            set {
                this.practitionerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime RegistrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistrationDateSpecified {
            get {
                return this.registrationDateFieldSpecified;
            }
            set {
                this.registrationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string ARRAReportableMeasures {
            get {
                return this.aRRAReportableMeasuresField;
            }
            set {
                this.aRRAReportableMeasuresField = value;
            }
        }
        
        /// <remarks/>
        public string ARRAPractitionerType {
            get {
                return this.aRRAPractitionerTypeField;
            }
            set {
                this.aRRAPractitionerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string NPINumber {
            get {
                return this.nPINumberField;
            }
            set {
                this.nPINumberField = value;
            }
        }
        
        /// <remarks/>
        public string TaxonomyCode {
            get {
                return this.taxonomyCodeField;
            }
            set {
                this.taxonomyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PractitionerLanguage {
            get {
                return this.practitionerLanguageField;
            }
            set {
                this.practitionerLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string ExcludeFromCalendar {
            get {
                return this.excludeFromCalendarField;
            }
            set {
                this.excludeFromCalendarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class PractitionerInformationObject {
        
        private System.DateTime dEAExpirationDateField;
        
        private bool dEAExpirationDateFieldSpecified;
        
        private string dEALicenseNumberField;
        
        private string socialSecurityNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DEAExpirationDate {
            get {
                return this.dEAExpirationDateField;
            }
            set {
                this.dEAExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DEAExpirationDateSpecified {
            get {
                return this.dEAExpirationDateFieldSpecified;
            }
            set {
                this.dEAExpirationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DEALicenseNumber {
            get {
                return this.dEALicenseNumberField;
            }
            set {
                this.dEALicenseNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SocialSecurityNumber {
            get {
                return this.socialSecurityNumberField;
            }
            set {
                this.socialSecurityNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class DictionaryItemObject {
        
        private string dictionaryCodeField;
        
        private string dictionaryFieldDescriptionField;
        
        private string dictionaryUniqueIdField;
        
        private string dictionaryValueField;
        
        private string mesgField;
        
        private string statusField;
        
        /// <remarks/>
        public string DictionaryCode {
            get {
                return this.dictionaryCodeField;
            }
            set {
                this.dictionaryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryFieldDescription {
            get {
                return this.dictionaryFieldDescriptionField;
            }
            set {
                this.dictionaryFieldDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryUniqueId {
            get {
                return this.dictionaryUniqueIdField;
            }
            set {
                this.dictionaryUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryValue {
            get {
                return this.dictionaryValueField;
            }
            set {
                this.dictionaryValueField = value;
            }
        }
        
        /// <remarks/>
        public string Mesg {
            get {
                return this.mesgField;
            }
            set {
                this.mesgField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class ResponseObject {
        
        private string confirmationField;
        
        private string messageField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        private string responseCodeField;
        
        private string uniqueIDField;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class WebServiceResponse {
        
        private string confirmationField;
        
        private string messageField;
        
        private string responseCodeField;
        
        private ResponseObject[] responseObjectsField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public ResponseObject[] ResponseObjects {
            get {
                return this.responseObjectsField;
            }
            set {
                this.responseObjectsField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EditPractitionerRegisterCompletedEventHandler(object sender, EditPractitionerRegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditPractitionerRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditPractitionerRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDictionaryItemsCompletedEventHandler(object sender, GetDictionaryItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDictionaryItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDictionaryItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DictionaryItemObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DictionaryItemObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PractitionerRegisterCompletedEventHandler(object sender, PractitionerRegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PractitionerRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PractitionerRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdatePractitionerInformationCompletedEventHandler(object sender, UpdatePractitionerInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePractitionerInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePractitionerInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591